name: Publish products from HyP3 to ASF

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
  EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD }}
  TOPIC_ARN: ${{ secrets.TOPIC_ARN }}
  RESPONSE_TOPIC_ARN: ${{ secrets.RESPONSE_TOPIC_ARN }}

jobs:
  publish-products:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - run: python -m pip install -r requirements.txt
      - run: |
          python publish_products_from_hyp3_to_asf.py \
          ${EARTHDATA_USERNAME} \
          ${EARTHDATA_PASSWORD} \
          ${TOPIC_ARN} \
          ${RESPONSE_TOPIC_ARN}
