name: Publish products from HyP3 to ASF

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  publish-products:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - environment: access19
            cmr_domain: https://cmr.earthdata.nasa.gov
            collection_concept_id: C1595422627-ASF
            hyp3_urls: https://hyp3-a19-jpl.asf.alaska.edu https://hyp3-tibet-jpl.asf.alaska.edu https://hyp3-nisar-jpl.asf.alaska.edu
            job_type: INSAR_ISCE

          - environment: disasters
            cmr_domain: https://cmr.earthdata.nasa.gov
            collection_concept_id: C1595422627-ASF
            hyp3_urls: https://hyp3-a19-jpl.asf.alaska.edu https://hyp3-tibet-jpl.asf.alaska.edu https://hyp3-nisar-jpl.asf.alaska.edu
            job_type: INSAR_ISCE

          - environment: access19-test
            cmr_domain: https://cmr.uat.earthdata.nasa.gov
            collection_concept_id: C1225776654-ASF
            hyp3_urls: https://hyp3-a19-jpl.asf.alaska.edu
            job_type: INSAR_ISCE_TEST

    environment: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - run: python -m pip install -r requirements.txt
      - run: |
          python publish_products_from_hyp3_to_asf.py \
          --cmr-domain ${{ matrix.cmr_domain }} \
          --collection-concept-id ${{ matrix.collection_concept_id }} \
          --hyp3-urls ${{ matrix.hyp3_urls }} \
          --job-type ${{ matrix.job_type }} \
          ${{ secrets.EARTHDATA_USERNAME }} \
          ${{ secrets.EARTHDATA_PASSWORD }} \
          ${{ secrets.TOPIC_ARN }} \
          ${{ secrets.RESPONSE_TOPIC_ARN }}
